services:
  db:
    image: postgres:16
    container_name: expense_tracker_db
    restart: always
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d expense_tracker" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Expense-Tracker
    container_name: expense_tracker_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
    ports:
      - "8080:8080"

volumes:
  postgres_data: